#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'os'
    style = 'diamond'
    foreground = '#ffffff'
    background = '#0c7bbb'
    leading_diamond = 'â•­â”€î‚²'
    template = ' {{ if .WSL }}îœ’ on {{ end }}{{ .Icon }}  '

    [blocks.segments.properties]
      alpine = 'ïŒ€'
      arch = 'ïŒƒ'
      centos = 'ïŒ„'
      debian = 'ïŒ†'
      elementary = 'ïŒ‰'
      fedora = 'ïŒŠ'
      gentoo = 'ïŒ'
      linux = 'îœ’'
      macos = 'îœ‘'
      manjaro = 'ïŒ’'
      mint = 'ïŒ'
      opensuse = 'ïŒ”'
      raspbian = 'ïŒ•'
      ubuntu = 'ïŒœ'
      windows = 'îœ'

  [[blocks.segments]]
    type = 'text'
    style = 'diamond'
    powerline_symbol = 'î‚°'
    foreground = '#ffffff'
    background = '#DA627D'
    template = ' ğŸ   '

  [[blocks.segments]]
    type = 'path'
    style = 'powerline'
    powerline_symbol = 'î‚°'
    foreground = '#ffffff'
    background = '#8a62da'
    template = ' {{ .Path }} '

    [blocks.segments.properties]
      style = 'folder'

  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = 'î‚°'
    foreground = '#43CCEA'
    foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#FF9248{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#ff4500{{ end }}', '{{ if gt .Ahead 0 }}#B388FF{{ end }}', '{{ if gt .Behind 0 }}#B388FF{{ end }}']
    background = '#191f48'
    trailing_diamond = 'î‚´'
    template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} ï„ {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }} ï† {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }} î­‹ {{ .StashCount }}{{ end }} '

    [blocks.segments.properties]
      branch_max_length = 25.0
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    type = 'sysinfo'
    style = 'diamond'
    foreground = '#81ff91'
    template = '<#cc7eda> | </><#7eb8da>RAM:</> {{ (div ((sub .PhysicalTotalMemory .PhysicalFreeMemory)|float64) 1073741824.0) }}/{{ (div .PhysicalTotalMemory 1073741824.0) }}GB'

  [[blocks.segments]]
    type = 'node'
    style = 'powerline'
    foreground = '#81ff91'
    template = '<#cc7eda> | </><#7eb8da>îœ˜</> {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }}'

    [blocks.segments.properties]
      fetch_version = true

  [[blocks.segments]]
    type = 'php'
    style = 'powerline'
    foreground = '#81ff91'
    template = '<#cc7eda> | </><#7eb8da>îœ½</> {{ .Full }}'

  [[blocks.segments]]
    type = 'npm'
    style = 'powerline'
    foreground = '#81ff91'
    template = '<#cc7eda> | </><#7eb8da>îœ </> {{ .Full }}'

  [[blocks.segments]]
    type = 'sysinfo'
    style = 'powerline'
    foreground = '#81ff91'
    template = '<> </>'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'diamond'
    foreground = '#4b4b4b'
    background = '#cecece'
    leading_diamond = 'î‚²'
    trailing_diamond = 'î‚°'
    template = 'âŒ›  {{ .FormattedMs }} '

    [blocks.segments.properties]
      style = 'austin'
      threshold = 150.0

  [[blocks.segments]]
    type = 'time'
    style = 'diamond'
    foreground = '#4b4b4b'
    background = '#cecece'
    leading_diamond = 'î‚²'
    trailing_diamond = 'î‚°'
    template = 'â°  {{ .CurrentDate | date .Format }} '

    [blocks.segments.properties]
      time_format = '15:04:05'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = '#0c7bbb'
    template = 'â•°â”€'
